require(rCharts)
shinyUI(
    pageWithSidebar(
        headerPanel("Multiscale local CP detector"),
        sidebarPanel(
            tabsetPanel(
                tabPanel("Parameters",
                    fluidPage(style = "padding-bottom: 20px;",                            
                        wellPanel(style = "overflow: auto; padding-bottom: 30px;",
                                  selectInput("input_type", h5("Real data:"),
                                             c("Gaussian", "Poisson", "Bernoulli")),                
                                     # This outputs the dynamic UI component
                                   uiOutput("ui"),
                                   uiOutput("ui_boot"),
                                   selectInput("pattern_control", h5("Pattern control:"),
                                             c("Triangle","Least squares" ,"Off")),
                                   hr(),
                                   actionButton('go', 'Start Demo', aligne = 'center')
                        ),
                        conditionalPanel(condition = 'input.go > 0',
                                        actionButton('realTime', 'Real time'),
                                        actionButton('timeAlign', 'Time Alignment'),
                                        hr()
                        )
                )),
                tabPanel("Control",
                    fluidPage(
                        wellPanel(style = "overflow: auto, padding-bottom: -10px;",
                                  h4('Automatic mode', aligne = 'center'),
                                  sliderInput("slider1", label = h5("Speed control"), min = 1, 
                                             max = 10, value = 7),
                                  actionButton('start', 'Start'),
                                  actionButton('stp', 'Pause')
                           ),
                        hr(),
                        wellPanel( h4('Manual mode'),
                                  numericInput("num", 
                                               label = h5("Add observations"), 
                                               value = 5),
                                  actionButton('add', 'Add')                      
                        )
                    )                
                )
            ),
            div(HTML("<br>This is a demo-version of multiscale change point detector
                    "))
            ),
    
            mainPanel(
                tabsetPanel(
                    tabPanel("Procedure",
                        htmlOutput('Splash'),
                        div(class = "row",
                             div(showOutput("realTimeData", 'highcharts'), class = "span12"), 
                             align = 'center'
                         ),
                        div(class = "row",
                             div(showOutput("realTimeStat1", 'highcharts'), class = "span12"),
                             align = 'center'                     
                        ),
                        div(class = "row",
                             div(showOutput("realTimeStat2", 'highcharts'), class = "span12"),
                             align = 'center'
                        ),
                        div(class = "row",
                             div(showOutput("realTimeStat3", 'highcharts'), class = "span12"),
                             align = 'center'
                        )
                    ),
                    
        tabPanel("How To",
                 HTML(
                     "<br>
                    <h5>Real data</h5> 
                    Observations can be generated by three different Markov sources:
                    <i>Gaussian</i>, <i>Poisson</i> and <i>Bernoulli</i>.
                    <hr>
                    <h5>Parametric model</h5>
                     One can choose one of three possible parametric assumptions:\n
                      <i>Gaussian (standard normal)</i>, <i>Poisson</i> or <i>Bernoulli</i>.
                    <hr>
                    <h5>Bootstrap</h5>
                     The drop-down menu \"Bootstrap\" allows to specifies the distribution of
                     multipliers in the bootstrap procedure.
                     <hr>
                    <h5>Pattern control</h5>
                    There are two possible ways of pattern control: convolution with a fixed half-triangle 
                    (<i>\"Triangle\"</i>), convolution with a fitted line (<i>\"Least squares\"</i>). One can also 
                    look at likelihood ratio test itself (<i>\"Off\"</i>).
                    <hr>
                    Some other control tools (<i>\"Pause\"</i>, <i>\"Continue\"</i>, and <i>\"Add\"</i> 
                    points manually) are avaliable by clicking <i>\"Control\"</i> tab."
                 )
        ),
        
        tabPanel("About the project",
                 HTML(
                     "<br>
                     <i> This demo illustrates the work of multisclae change point detector. 
                     The algorithm computes likelihood ratio test in a running window, which 
                     exhibits a specific behavior (pattern) in the vicinity of a change point,
                     depending on the type of a structural change. 
                     Monitoring of patterns instead of just using the 
                     likelihood-ratio test improves sensitivity of 
                     change point detection and robustness to outliers. 
                     To make method adaptive to change point of different sizes, multiscale approach is proposed. 
                     Calibration of critical values is done in a data-driven way using multiplier bootstrap
                     and does not require a homogeneous training sample.
                     <h5>About us:</h5>
                      <a href='https://irtg1792.hu-berlin.de/' target='_blank'>IRTG 1792</a>
                      <br>
                      <a href='http://www.wias-berlin.de/research/rgs/fg6/' target='_blank'>WIAS</a>"
                 )
        )
        )
        )
    )
)